import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from '@/providers/StoreProvider';
import { Menu } from '@/widgets';
import MainProvider from '@/providers/MainProvider';
import { getAllPages } from '@/features';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pagesList = getAllPages();

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <MainProvider>
            <Menu pagesList={pagesList} />
            {children}
          </MainProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
