import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.scss';
import StoreProvider from '@/providers/StoreProvider';
import { Menu } from '@/widgets';
import MainProvider from '@/providers/MainProvider';
import { getAllPages } from '@/features';

const font = localFont({
  src: '../../style/fonts/Open Sans/OpenSans-VariableFont_wdth,wght.ttf',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const pagesList = getAllPages();

  return (
    <html lang={locale}>
      <body className={font.className}>
        <StoreProvider>
          <MainProvider>
            <Menu pagesList={pagesList} locale={locale} />
            {children}
          </MainProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
