import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.scss';
import { Menu } from '@/widgets';
import { getAllPages } from '@/features';
import { MainProvider, StoreProvider, ThemeProvider } from '@/providers';

const font = localFont({
  src: '../../style/fonts/Open Sans/OpenSans-VariableFont_wdth,wght.ttf',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const pagesList = getAllPages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={font.className}>
        <StoreProvider>
          <ThemeProvider>
            <MainProvider>
              <Menu pagesList={pagesList} locale={locale} />
              {children}
            </MainProvider>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
